# WhatATheme
markdown: kramdown

# URL of the Site
url: ""
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Confessions of a Chipotle Addict
# Description of the Site
#description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Chipotle, Addict, Guacamole, Extra Meat, Chips and Salsa
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/sdecsesznak/sdecsesznak.github.io/raw/master/assets/images/Front_Page.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: guaconmyface@gmail.com
#facebook_username: /
#twitter_username: /
#instagram_username: /
#linkedin_username: /
github_username:  sdecsesznak
#youtube_channel_id: /
#reddit_username: /
#behance_username: /
#dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-179038535-1

# Disqus
# disqus-shortname: ChipotleAddict

# Name of the Author
author-name: Steven
# URL for the Image of the Author
author-image: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
# 60 Words About the Author
author-about: Hi, ny name is Steven and I am a Chipotle Addict.  In an effort to advance my campaign in unlocking Chipotle's VIP card, I have put together this website to document the letters that I write to Chipotle.  
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/sdeCsesznak

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "letter/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
